### PR TITLE
Configure site base for Heroku deployment

### PR DESCRIPTION
**Pull request by rzumer**
* Add requirements.txt for dependency management
* Add runtime.txt to specify a Python runtime
* Specify character encoding in eHall/auditorium/models.py to solve a runtime error
* Update settings.py:
  * Remove redundant call to os.path.dirname()
  * Change database authentication password to match README.md
  * Add STATIC_ROOT declaration
  * Add basic configuration for dj_database_url to connect to the Heroku database (should not impact local deployment)

Windows environment configuration instructions: http://pastebin.com/CF2rpZ6y (then follow the steps outlined in `README.md`).

Whenever a new dependency is generated, `requirements.txt` must be updated via the following command: `pip freeze > requirements.txt` (at the root directory of the application).

Feel free to squash.

### CODE REVIEW

**Comment by gzsierra** [comment]
Please remove all binary file from your Pull Request.
Compiled file like `.pyc` should **not** be added, please check the file [.gitignore](https://github.com/gti525/h17-gestionnaire-salle/blob/feat/base_site/.gitignore)

**Comment by rzumer** [comment]
Removed *.pyc.

**Comment by rzumer** [comment]
Fixed Heroku deployment with the last commit. Please squash all the unmerged commits if the pull request is OK.

**Comment by rzumer** [comment]
Last commit solves database connection issues by splitting the local and production configuration settings.

**Comment by gzsierra** [comment]
All the code has been merge in Master.
Need approbation to remove branch `feat/base_site`

**Comment by rzumer** [comment]
I don't see anything merged since 92cc806.

**Pull request merged**
